server:
  port: 8001
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    appname: eurekaserver
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/8001/eureka
    register-with-eureka: false
    fetch-registry: false
